version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      # TODO: Criar .env para credenciais 
      POSTGRES_USER: gchsantos
      POSTGRES_PASSWORD: itawesome
      POSTGRES_DB: jusbrasil_challenge
      TZ: GMT+3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gchsantos -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - back-tier

volumes:
  postgres-data:


networks:
  back-tier:
